---
apollo_deps:
    - ssl-cert
    - lsb-release
    - curl
    - wget
    - netcat-traditional
    - git
    - zip
    - unzip
    - build-essential
    - python3-pip
    - libpq-dev
    - gnupg2
    - xmlstarlet
    - libpng-dev
    - zlib1g-dev
    - libexpat1-dev
    - ant
    - ack # also includes libfile-next-perl required by generate-names.pl
    - atop
    - tree
    - plocate
    - net-tools
    - samtools
    - ncbi-blast+

